import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);
const daysFromNow = (n: number) => new Date(now.getTime() + n * 24 * 60 * 60 * 1000);

async function main() {
  console.log('Seeding aligned SAHAY cases & check-ins...');

  const passwordHash = await bcrypt.hash('Demo@1234', 12);

  // Ensure default demo users exist
  const officer = await prisma.user.upsert({
    where: { email: 'officer.lucknow@sahay.demo' },
    update: {},
    create: {
      id: 'usr-officer-01',
      email: 'officer.lucknow@sahay.demo',
      passwordHash,
      name: 'Dr. Rajesh Verma',
      role: 'district_officer',
      district: 'Lucknow',
      state: 'Uttar Pradesh',
      language: 'hi',
    },
  });

  const counsellor = await prisma.user.upsert({
    where: { email: 'counsellor.a@sahay.demo' },
    update: {},
    create: {
      id: 'usr-counsellor-01',
      email: 'counsellor.a@sahay.demo',
      passwordHash,
      name: 'Priya Sharma',
      role: 'counsellor',
      district: 'Lucknow',
      state: 'Uttar Pradesh',
      language: 'hi',
    },
  });

  const alignedCases = [
    {
      id: 'case-001',
      caseRef: 'UP-LKO-2026-0842',
      personNameMasked: 'R.K. (Victim #01)',
      personInitials: 'RK',
      district: 'Lucknow',
      state: 'Uttar Pradesh',
      block: 'Bakshi Ka Talab',
      caseStage: 'trial',
      caseType: 'victim',
      riskLevel: 'critical',
      distressScore: 84,
      trend: 'worsening',
      lastCheckIn: daysAgo(1),
      lastContact: daysAgo(1),
      nextAction: 'Provide urgent physical witness protection & emergency counselling session before trial hearing on 18 Sep',
      nextActionDue: daysFromNow(1),
      checkInCompletionRate: 92,
      dataConfidence: 'high',
      dataFreshnessHours: 4,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Victim under Section 3(1)(r)(s) SC/ST PoA Act. Cross-examination scheduled in Special Court next week.',
    },
    {
      id: 'case-002',
      caseRef: 'MH-PUN-2026-0319',
      personNameMasked: 'S.M. (Complainant #02)',
      personInitials: 'SM',
      district: 'Pune',
      state: 'Maharashtra',
      block: 'Haveli',
      caseStage: 'investigation',
      caseType: 'complainant',
      riskLevel: 'high',
      distressScore: 72,
      trend: 'worsening',
      lastCheckIn: daysAgo(2),
      lastContact: daysAgo(2),
      nextAction: 'Expedite IO chargesheet submission; verify CCTV footage near work premise',
      nextActionDue: daysFromNow(2),
      checkInCompletionRate: 85,
      dataConfidence: 'high',
      dataFreshnessHours: 28,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Complainant reported economic boycott and refusal of water access following FIR filing.',
    },
    {
      id: 'case-003',
      caseRef: 'RJ-JPR-2026-0158',
      personNameMasked: 'M.B. (Witness #03)',
      personInitials: 'MB',
      district: 'Jaipur',
      state: 'Rajasthan',
      block: 'Amber',
      caseStage: 'trial',
      caseType: 'witness',
      riskLevel: 'critical',
      distressScore: 89,
      trend: 'worsening',
      lastCheckIn: daysAgo(1),
      lastContact: daysAgo(1),
      nextAction: 'Court escort deployment and secure transit for deposition on 16 Sep',
      nextActionDue: daysFromNow(1),
      checkInCompletionRate: 95,
      dataConfidence: 'high',
      dataFreshnessHours: 8,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Key eyewitness to incident under trial. Direct intimidation by accused relatives reported.',
    },
    {
      id: 'case-004',
      caseRef: 'TN-CHE-2026-0491',
      personNameMasked: 'K.T. (Victim #04)',
      personInitials: 'KT',
      district: 'Chennai',
      state: 'Tamil Nadu',
      block: 'Alandur',
      caseStage: 'compensation',
      caseType: 'victim',
      riskLevel: 'moderate',
      distressScore: 54,
      trend: 'improving',
      lastCheckIn: daysAgo(3),
      lastContact: daysAgo(5),
      nextAction: 'Disburse second tranche of victim rehabilitation relief (₹4,12,500)',
      nextActionDue: daysFromNow(7),
      checkInCompletionRate: 78,
      dataConfidence: 'high',
      dataFreshnessHours: 42,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Chargesheet filed in Special Court. 50% initial relief credited.',
    },
    {
      id: 'case-005',
      caseRef: 'UP-AGR-2026-0612',
      personNameMasked: 'G.P. (Victim #05)',
      personInitials: 'GP',
      district: 'Agra',
      state: 'Uttar Pradesh',
      block: 'Fatehabad',
      caseStage: 'rehabilitation',
      caseType: 'victim',
      riskLevel: 'low',
      distressScore: 28,
      trend: 'improving',
      lastCheckIn: daysAgo(2),
      lastContact: daysAgo(8),
      nextAction: 'Skill training enrolment under PM-DAKSH scheme and monthly check-in review',
      nextActionDue: daysFromNow(12),
      checkInCompletionRate: 88,
      dataConfidence: 'high',
      dataFreshnessHours: 22,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Rehabilitation phase. Residential relocation completed smoothly.',
    },
    {
      id: 'case-006',
      caseRef: 'WB-KOL-2026-0274',
      personNameMasked: 'A.D. (Complainant #06)',
      personInitials: 'AD',
      district: 'Kolkata',
      state: 'West Bengal',
      block: 'South 24 Parganas',
      caseStage: 'investigation',
      caseType: 'complainant',
      riskLevel: 'high',
      distressScore: 68,
      trend: 'stable',
      lastCheckIn: daysAgo(4),
      lastContact: daysAgo(6),
      nextAction: 'Medical board assessment report follow-up; ensure free legal aid lawyer assignment',
      nextActionDue: daysFromNow(3),
      checkInCompletionRate: 70,
      dataConfidence: 'medium',
      dataFreshnessHours: 72,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Investigation in progress. Delayed response to check-in prompts due to intermittent connectivity.',
    },
    {
      id: 'case-007',
      caseRef: 'MP-BPL-2026-0931',
      personNameMasked: 'N.S. (Victim #07)',
      personInitials: 'NS',
      district: 'Bhopal',
      state: 'Madhya Pradesh',
      block: 'Berasia',
      caseStage: 'registration',
      caseType: 'victim',
      riskLevel: 'high',
      distressScore: 76,
      trend: 'worsening',
      lastCheckIn: daysAgo(1),
      lastContact: daysAgo(1),
      nextAction: 'First tranche relief sanction (25% upon FIR) within 7 days mandatory timeline',
      nextActionDue: daysFromNow(2),
      checkInCompletionRate: 100,
      dataConfidence: 'high',
      dataFreshnessHours: 1,
      privacyMasked: true,
      consentGiven: true,
      notes: 'FIR registered under Section 3(1)(w) & IPC 354. Acute trauma reported.',
    },
    {
      id: 'case-008',
      caseRef: 'RJ-UDR-2026-0417',
      personNameMasked: 'B.L. (Victim #08)',
      personInitials: 'BL',
      district: 'Udaipur',
      state: 'Rajasthan',
      block: 'Kotra',
      caseStage: 'witness_protection',
      caseType: 'victim',
      riskLevel: 'critical',
      distressScore: 91,
      trend: 'worsening',
      lastCheckIn: daysAgo(1),
      lastContact: daysAgo(1),
      nextAction: 'Emergency safe-house transfer; notify SP for dedicated armed guard roster',
      nextActionDue: daysFromNow(1),
      checkInCompletionRate: 94,
      dataConfidence: 'high',
      dataFreshnessHours: 9,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Severe intimidation attempt thwarted by local beat officer. Immediate protection ordered.',
    },
    {
      id: 'case-009',
      caseRef: 'MH-NAG-2026-0523',
      personNameMasked: 'V.W. (Complainant #09)',
      personInitials: 'VW',
      district: 'Nagpur',
      state: 'Maharashtra',
      block: 'Ramtek',
      caseStage: 'trial',
      caseType: 'complainant',
      riskLevel: 'moderate',
      distressScore: 48,
      trend: 'stable',
      lastCheckIn: daysAgo(3),
      lastContact: daysAgo(7),
      nextAction: 'Review witness protection measures ahead of upcoming trial date on 28 Sep',
      nextActionDue: daysFromNow(9),
      checkInCompletionRate: 80,
      dataConfidence: 'high',
      dataFreshnessHours: 48,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Trial ongoing in Special Sessions Court. Complainant receiving bi-weekly counselling.',
    },
    {
      id: 'case-010',
      caseRef: 'MP-IND-2026-0789',
      personNameMasked: 'T.J. (Victim #10)',
      personInitials: 'TJ',
      district: 'Indore',
      state: 'Madhya Pradesh',
      block: 'Mhow',
      caseStage: 'compensation',
      caseType: 'victim',
      riskLevel: 'low',
      distressScore: 32,
      trend: 'improving',
      lastCheckIn: daysAgo(2),
      lastContact: daysAgo(9),
      nextAction: 'Final instalment compensation release verification with Treasury',
      nextActionDue: daysFromNow(11),
      checkInCompletionRate: 90,
      dataConfidence: 'high',
      dataFreshnessHours: 26,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Conviction secured in trial. Compensation disbursement ongoing.',
    },
    {
      id: 'case-011',
      caseRef: 'UP-LKO-2026-0911',
      personNameMasked: 'H.C. (Witness #11)',
      personInitials: 'HC',
      district: 'Lucknow',
      state: 'Uttar Pradesh',
      block: 'Mohanlalganj',
      caseStage: 'investigation',
      caseType: 'witness',
      riskLevel: 'moderate',
      distressScore: 61,
      trend: 'stable',
      lastCheckIn: daysAgo(5),
      lastContact: daysAgo(5),
      nextAction: 'Schedule home visit by field worker to address missed IVRS check-in',
      nextActionDue: daysFromNow(3),
      checkInCompletionRate: 65,
      dataConfidence: 'medium',
      dataFreshnessHours: 96,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Witness in Section 3(2)(v) investigation. Phone frequently unreachable during daytime.',
    },
    {
      id: 'case-012',
      caseRef: 'RJ-JPR-2026-0688',
      personNameMasked: 'D.R. (Victim #12)',
      personInitials: 'DR',
      district: 'Jaipur',
      state: 'Rajasthan',
      block: 'Sanganer',
      caseStage: 'closed',
      caseType: 'victim',
      riskLevel: 'low',
      distressScore: 19,
      trend: 'improving',
      lastCheckIn: daysAgo(14),
      lastContact: daysAgo(12),
      nextAction: 'Annual post-closure welfare review (scheduled March 2027)',
      nextActionDue: daysFromNow(170),
      checkInCompletionRate: 98,
      dataConfidence: 'high',
      dataFreshnessHours: 320,
      privacyMasked: true,
      consentGiven: true,
      notes: 'Case successfully concluded with full rehabilitation, livelihood grant, and compensation.',
    },
  ];

  for (const c of alignedCases) {
    await prisma.case.upsert({
      where: { id: c.id },
      update: {
        distressScore: c.distressScore,
        riskLevel: c.riskLevel,
        lastCheckIn: c.lastCheckIn,
        lastContact: c.lastContact,
        nextAction: c.nextAction,
        nextActionDue: c.nextActionDue,
        caseStage: c.caseStage,
        caseRef: c.caseRef,
      },
      create: {
        id: c.id,
        caseRef: c.caseRef,
        personNameMasked: c.personNameMasked,
        personInitials: c.personInitials,
        district: c.district,
        state: c.state,
        block: c.block,
        caseStage: c.caseStage,
        caseType: c.caseType,
        assignedOfficerId: officer.id,
        assignedCounsellorId: counsellor.id,
        riskLevel: c.riskLevel,
        distressScore: c.distressScore,
        trend: c.trend,
        lastCheckIn: c.lastCheckIn,
        lastContact: c.lastContact,
        nextAction: c.nextAction,
        nextActionDue: c.nextActionDue,
        checkInCompletionRate: c.checkInCompletionRate,
        dataConfidence: c.dataConfidence,
        dataFreshnessHours: c.dataFreshnessHours,
        privacyMasked: c.privacyMasked,
        consentGiven: c.consentGiven,
        notes: c.notes,
      },
    });
  }

  console.log(`Upserted ${alignedCases.length} cases with deterministic IDs.`);

  // Initial check-ins for case-001
  const existingCheckIns = await prisma.checkIn.count({ where: { caseId: 'case-001' } });
  if (existingCheckIns === 0) {
    await prisma.checkIn.createMany({
      data: [
        {
          id: 'chk-001',
          caseId: 'case-001',
          submittedAt: daysAgo(1),
          channel: 'web',
          completionStatus: 'complete',
          distressIndicator: 84,
          riskLevel: 'critical',
          consentGiven: true,
          responses: JSON.stringify({
            feelingRating: 1,
            feelingLabel: 'Very distressed / severely anxious',
            feelingUnsafe: true,
            intimidatedRecently: true,
            sleepQuality: 1,
            appetite: 2,
            ableToAttendWork: false,
            ableToAttendAppointments: true,
            supportNeeds: ['Immediate physical safety', 'Trauma counselling', 'Legal assistance for court hearing'],
            additionalNotes: 'Two unknown persons stopped outside our gate yesterday and asked for me by name.',
          }),
          humanReviewStatus: 'escalated',
          flaggedForEscalation: true,
        },
        {
          id: 'chk-002',
          caseId: 'case-001',
          submittedAt: daysAgo(5),
          channel: 'ivrs',
          completionStatus: 'complete',
          distressIndicator: 62,
          riskLevel: 'moderate',
          consentGiven: true,
          responses: JSON.stringify({
            feelingRating: 2,
            feelingLabel: 'Struggling / uneasy',
            feelingUnsafe: false,
            intimidatedRecently: false,
            sleepQuality: 2,
            appetite: 3,
            ableToAttendWork: true,
            ableToAttendAppointments: true,
            supportNeeds: ['Counselling follow-up'],
          }),
          humanReviewStatus: 'reviewed',
          flaggedForEscalation: false,
        },
      ],
    });
    console.log('Created initial check-ins for case-001.');
  }

  // Initial alerts
  const existingAlerts = await prisma.alert.count();
  if (existingAlerts === 0) {
    await prisma.alert.createMany({
      data: [
        {
          id: 'alt-001',
          caseId: 'case-001',
          alertType: 'intimidation_reported',
          severity: 'critical',
          triggerDescription: 'Victim submitted emergency check-in flagging direct physical threat near home ahead of trial date',
          detectedAt: daysAgo(1),
          recommendedAction: 'Immediate police patrol dispatch & assign round-the-clock witness protection officer under Rule 12',
          slaDue: daysFromNow(0),
          status: 'new',
        },
        {
          id: 'alt-002',
          caseId: 'case-008',
          alertType: 'distress_increase',
          severity: 'critical',
          triggerDescription: 'Distress score spiked from 52 to 91 (+39 points) over 72 hours; safety concern flagged as true',
          detectedAt: daysAgo(1),
          recommendedAction: 'Immediate safe-house relocation & emergency psychiatric consultation',
          slaDue: daysFromNow(0),
          status: 'acknowledged',
        },
        {
          id: 'alt-003',
          caseId: 'case-003',
          alertType: 'court_approaching',
          severity: 'high',
          triggerDescription: 'Key deposition date in Special Court in 3 days; witness reported acute sleep disruption and high anxiety',
          detectedAt: daysAgo(1),
          recommendedAction: 'Provide trauma-informed court preparation session & verify witness protection protocol with SP office',
          slaDue: daysFromNow(1),
          status: 'assigned',
        },
      ],
    });
    console.log('Created initial alerts.');
  }

  console.log('Database seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
